from datetime import datetime, timedelta
today = datetime.today()
print(f"Today is :  {today}.")

print("Halloumi Sticks")
print(datetime.now() + timedelta(days=3))
print("Cheese")
print(datetime.now() + timedelta(days=2))
print("Halloumi Slices")
print(datetime.now() + timedelta(days=4))
print("Lettuce")
print(datetime.now() + timedelta(days=1))
print("Salad Leaf")
print(datetime.now() + timedelta(days=1))
print("Garlic Spread")
print(datetime.now() + timedelta(days=2))
print("Big tub of Garlic Spread")
print(datetime.now() + timedelta(days=7))
print("Lemon Mayo")
print(datetime.now() + timedelta(days=9))
print("Ketchup")
print(datetime.now() + timedelta(days=9))
print("Caramelised Onion")
print(datetime.now() + timedelta(days=13))
print("Yoghurt Mayo")
print(datetime.now() + timedelta(days=6))
print("Garlic Aioli")
print(datetime.now() + timedelta(days=9))
print("Garlic Perinnaise")
print(datetime.now() + timedelta(days=10))
print("Churasco Perinnaise")
print(datetime.now() + timedelta(days=10))
print("Rainbow Slaw")
print(datetime.now() + timedelta(days=1))
print("Pineapple")
print(datetime.now() + timedelta(days=1))
print("Mushroom")
print(datetime.now() + timedelta(days=1))
print("Pickled Onion")
print("Check Packaging")
print("Chilli Jam")
print(datetime.now() + timedelta(days=10))
print("Peri Tamer")
print(datetime.now() + timedelta(days=30))
print("Liver Baste")
print(datetime.now() + timedelta(days=28))
print("Red Pepper Chutney")
print("Check Packaging")
print("Bolo")
print(datetime.now() + timedelta(days=1))
